-- auto-generated definition
CREATE SCHEMA IF NOT EXISTS SYSADMIN_CHAT_BOT;
SET SEARCH_PATH = SYSADMIN_CHAT_BOT, PUBLIC;


ALTER TABLE CHATS RENAME TO CHATS_OLD;
ALTER TABLE CHATS_OLD RENAME CONSTRAINT CHATS_PKEY TO CHATS_OLD_PKEY;
CREATE TABLE CHATS
(
    ID                    BIGINT PRIMARY KEY,
    TYPE                  TEXT NOT NULL,
    TITLE                 TEXT,
    INVITE_LINK           TEXT,
    PERMISSIONS           JSONB,
    JOIN_TO_SEND_MESSAGES BOOLEAN,
    MAX_REACTION_COUNT    INTEGER,
    RAW                   JSONB
);
COMMENT ON TABLE CHATS IS 'This table represents a chat.';
COMMENT ON COLUMN CHATS.ID IS 'Unique identifier for this chat. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this identifier.';
COMMENT ON COLUMN CHATS.TYPE IS 'Type of the chat, can be either “private”, “group”, “supergroup” or “channel”';
COMMENT ON COLUMN CHATS.TITLE IS 'Optional. Title, for supergroups, channels and group chats';
COMMENT ON COLUMN CHATS.RAW IS 'RAW answer from telegram';
INSERT INTO CHATS (ID, TYPE, TITLE, INVITE_LINK, PERMISSIONS, JOIN_TO_SEND_MESSAGES, MAX_REACTION_COUNT, RAW)
SELECT ID, TYPE, TITLE, INVITE_LINK, PERMISSIONS, JOIN_TO_SEND_MESSAGES, MAX_REACTION_COUNT, RAW FROM CHATS_OLD ORDER BY ID
ON CONFLICT DO NOTHING;

------------------

ALTER TABLE USERS RENAME TO USERS_OLD;
ALTER TABLE USERS_OLD RENAME CONSTRAINT USERS_PKEY TO USERS_OLD_PKEY;
CREATE TABLE USERS
(
    ID                   BIGINT PRIMARY KEY,
    USERNAME             TEXT,
    FIRST_NAME           TEXT NOT NULL,
    LAST_NAME            TEXT,
    TYPE                 TEXT,
    ACTIVE_USERNAMES     TEXT[],
    BIO                  TEXT,
    HAS_PRIVATE_FORWARDS BOOLEAN,
    MAX_REACTION_COUNT   INTEGER,
    ACCENT_COLOR_ID      INTEGER,
    RAW                  JSONB
);
COMMENT ON TABLE USERS IS 'This table represents a Telegram user or bot.';
COMMENT ON COLUMN USERS.ID IS 'Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.';
COMMENT ON COLUMN USERS.USERNAME IS 'Optional. User''s or bot''s username';
COMMENT ON COLUMN USERS.FIRST_NAME IS 'User''s or bot''s first name';
COMMENT ON COLUMN USERS.LAST_NAME IS 'Optional. User''s or bot''s last name';
COMMENT ON COLUMN USERS.RAW IS 'RAW answer from telegram';
INSERT INTO USERS (ID, USERNAME, FIRST_NAME, LAST_NAME, TYPE, ACTIVE_USERNAMES, BIO, HAS_PRIVATE_FORWARDS, MAX_REACTION_COUNT, ACCENT_COLOR_ID, RAW)
SELECT ID, USERNAME, FIRST_NAME, LAST_NAME, TYPE, ACTIVE_USERNAMES, BIO, HAS_PRIVATE_FORWARDS, MAX_REACTION_COUNT, ACCENT_COLOR_ID, RAW FROM USERS_OLD ORDER BY ID
ON CONFLICT DO NOTHING;

------------------

ALTER TABLE USERS_CHATS RENAME TO USERS_CHATS_OLD;
ALTER TABLE USERS_CHATS_OLD RENAME CONSTRAINT USERS_CHATS_PKEY TO USERS_CHATS_OLD_PKEY;
ALTER TABLE USERS_CHATS_OLD RENAME CONSTRAINT USERS_CHATS_CHAT_ID_FKEY TO USERS_CHATS_OLD_CHAT_ID_FKEY;
ALTER TABLE USERS_CHATS_OLD RENAME CONSTRAINT USERS_CHATS_USER_ID_FKEY TO USERS_CHATS_OLD_USER_ID_FKEY;
CREATE TABLE USERS_CHATS
(
    USER_ID    BIGINT                NOT NULL REFERENCES USERS ON UPDATE CASCADE ON DELETE CASCADE,
    CHAT_ID    BIGINT                NOT NULL REFERENCES CHATS ON UPDATE CASCADE ON DELETE CASCADE,
    NEW_USER   BOOLEAN DEFAULT TRUE  NOT NULL,
    IS_BLOCKED BOOLEAN DEFAULT FALSE NOT NULL,
    PRIMARY KEY (USER_ID, CHAT_ID)
);
COMMENT ON TABLE USERS_CHATS IS 'This table represents a Telegram user in chat.';
COMMENT ON COLUMN USERS_CHATS.USER_ID IS 'Unique identifier for this user or bot. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a 64-bit integer or double-precision float type are safe for storing this identifier.';
COMMENT ON COLUMN USERS_CHATS.CHAT_ID IS 'Unique identifier for this chat. This number may have more than 32 significant bits and some programming languages may have difficulty/silent defects in interpreting it. But it has at most 52 significant bits, so a signed 64-bit integer or double-precision float type are safe for storing this identifier.';
COMMENT ON COLUMN USERS_CHATS.NEW_USER IS 'True if user is new for this chats and not accepted chats rules';
INSERT INTO USERS_CHATS (USER_ID, CHAT_ID, NEW_USER, IS_BLOCKED)
SELECT USER_ID, CHAT_ID, NEW_USER, IS_BLOCKED FROM USERS_CHATS_OLD ORDER BY USER_ID, CHAT_ID
ON CONFLICT DO NOTHING;

------------------

ALTER TABLE FINES RENAME TO FINES_OLD;
ALTER TABLE FINES_OLD RENAME CONSTRAINT FINES_PKEY TO FINES_OLD_PKEY;
ALTER SEQUENCE FINES_ID_SEQ RENAME TO FINES_OLD_ID_SEQ;
CREATE TABLE FINES
(
    ID          SERIAL PRIMARY KEY,
    NAME        TEXT NOT NULL UNIQUE,
    DESCRIPTION TEXT
);
COMMENT ON TABLE FINES IS 'This table represents a user fines types';
COMMENT ON COLUMN FINES.ID IS 'Fines description.';
INSERT INTO FINES (NAME, DESCRIPTION)
SELECT NAME, DESCRIPTION FROM FINES_OLD ORDER BY NAME;
INSERT INTO FINES(NAME, DESCRIPTION)
VALUES ('SPAM', 'Detect SPAM messages')
ON CONFLICT DO NOTHING;
DO
$$
    DECLARE
        MAX_ID INT;
    BEGIN
        MAX_ID := (SELECT COALESCE(MAX(ID), 0) + 1 FROM FINES);
        EXECUTE FORMAT('ALTER SEQUENCE FINES_ID_SEQ START WITH %s RESTART;', MAX_ID);
    END;
$$;

------------------

ALTER TABLE USER_FINES RENAME TO USER_FINES_OLD;
CREATE TABLE IF NOT EXISTS USER_FINES
(
    USER_ID     BIGINT                  NOT NULL REFERENCES USERS ON UPDATE CASCADE ON DELETE CASCADE,
    CHAT_ID     BIGINT                  NOT NULL REFERENCES CHATS ON UPDATE CASCADE ON DELETE CASCADE,
    TIMESTAMP   TIMESTAMP DEFAULT NOW() NOT NULL,
    TYPE        INTEGER                 NOT NULL REFERENCES FINES ON UPDATE CASCADE ON DELETE CASCADE,
    DESCRIPTION TEXT,
    PRIMARY KEY (USER_ID, CHAT_ID, TIMESTAMP, TYPE)
);
COMMENT ON TABLE USER_FINES IS 'This table contains a user fines incidents';
CREATE INDEX IDX_USER_FINES_USER_ID_CHAT_ID_TIMESTAMP ON USER_FINES (USER_ID, CHAT_ID, TIMESTAMP);
INSERT INTO USER_FINES (USER_ID, CHAT_ID, TIMESTAMP, TYPE, DESCRIPTION)
SELECT USER_ID, CHAT_ID, TIMESTAMP, TYPE, DESCRIPTION FROM USER_FINES_OLD ORDER BY USER_ID, CHAT_ID;

------------------

ALTER TABLE ACTIONS RENAME TO ACTIONS_OLD;
CREATE TABLE IF NOT EXISTS ACTIONS
(
    ACTION      TEXT PRIMARY KEY,
    DESCRIPTION TEXT
);
INSERT INTO ACTIONS (ACTION, DESCRIPTION)
SELECT ACTION, DESCRIPTION FROM ACTIONS_OLD ORDER BY ACTION;

------------------

ALTER TABLE COMMANDS RENAME TO COMMANDS_OLD;
CREATE TABLE IF NOT EXISTS COMMANDS
(
    COMMAND     TEXT PRIMARY KEY,
    DESCRIPTION TEXT
);
INSERT INTO COMMANDS (COMMAND, DESCRIPTION)
SELECT COMMAND, DESCRIPTION FROM COMMANDS_OLD ORDER BY COMMAND;

------------------

ALTER TABLE MESSAGES RENAME TO MESSAGES_OLD;
CREATE TABLE IF NOT EXISTS MESSAGES
(
    MESSAGE_ID BIGINT PRIMARY KEY,
    CHAT_ID    BIGINT                  NOT NULL REFERENCES CHATS ON UPDATE CASCADE ON DELETE CASCADE,
    USER_ID    BIGINT                  NOT NULL REFERENCES USERS ON UPDATE CASCADE ON DELETE CASCADE,
    TIMESTAMP  TIMESTAMP DEFAULT NOW() NOT NULL,
    MESSAGE    JSONB                   NOT NULL,
    CTX        JSONB
);
COMMENT ON TABLE USER_FINES IS 'This table contains a user messages';
CREATE INDEX IDX_MESSAGE_CHAT_ID_USER_ID ON MESSAGES (CHAT_ID, USER_ID);
CREATE INDEX IDX_MESSAGE_CTX ON MESSAGES USING GIN (CTX);
INSERT INTO MESSAGES (MESSAGE_ID, CHAT_ID, USER_ID, TIMESTAMP, MESSAGE, CTX)
SELECT MESSAGE_ID, CHAT_ID, USER_ID, TIMESTAMP, MESSAGE, CTX FROM MESSAGES_OLD ORDER BY MESSAGE_ID;

------------------

ALTER TABLE CHATS_USERS_TEST_QUESTION RENAME TO CHATS_USERS_TEST_QUESTION_OLD;
CREATE TABLE IF NOT EXISTS CHATS_USERS_TEST_QUESTION
(
    CHAT_ID BIGINT NOT NULL REFERENCES CHATS ON UPDATE CASCADE ON DELETE CASCADE,
    USER_ID BIGINT NOT NULL REFERENCES USERS ON UPDATE CASCADE ON DELETE CASCADE,
    ANSWER  TEXT   NOT NULL,
    PRIMARY KEY (CHAT_ID, USER_ID)
);
INSERT INTO CHATS_USERS_TEST_QUESTION (CHAT_ID, USER_ID, ANSWER)
SELECT CHAT_ID, USER_ID, ANSWER FROM CHATS_USERS_TEST_QUESTION_OLD ORDER BY CHAT_ID, USER_ID;

------------------

CREATE TABLE AIS
(
    ID    SERIAL PRIMARY KEY,
    NAME  TEXT NOT NULL UNIQUE,
    DESCR TEXT
);
INSERT INTO AIS (NAME, DESCR)
VALUES ('deepseek', 'DeepSeek'),
       ('chatGPT', 'ChatGPT')
ON CONFLICT DO NOTHING;

------------------

ALTER TABLE AI_KINDS RENAME TO AI_KINDS_OLD;
CREATE TABLE IF NOT EXISTS AI_KINDS
(
    ID    SMALLSERIAL PRIMARY KEY,
    NAME  TEXT NOT NULL UNIQUE,
    DESCR TEXT
);
INSERT INTO AI_KINDS (ID, NAME, DESCR)
SELECT ID, NAME, DESCR FROM AI_KINDS_OLD ORDER BY ID;
INSERT INTO AI_KINDS (ID, NAME, DESCR)
VALUES (1, 'is_spam', 'Проверка сообщения на SPAM'),
       (2, 'message', 'Сообщение'),
       (3, 'test_message', 'Тестовое сообщение')
ON CONFLICT DO NOTHING;



CREATE TABLE IF NOT EXISTS AI_MODELS
(
    ID   SMALLSERIAL PRIMARY KEY,
    NAME TEXT NOT NULL UNIQUE,
    AI   INT  NOT NULL REFERENCES AIS ON UPDATE CASCADE ON DELETE SET NULL
);
INSERT INTO AI_MODELS (ID, NAME, AI)
VALUES (1, 'deepseek-reasoner', 1),
       (2, 'deepseek-chat', 1),
       (3, 'gpt-5.4-nano', 2)
ON CONFLICT DO NOTHING;

CREATE TABLE IF NOT EXISTS AI_REQUEST
(
    ID                SERIAL PRIMARY KEY,
    REQUEST_TIMESTAMP TIMESTAMP DEFAULT NOW() NOT NULL,
    REQUEST           JSONB,
    ANSWER_TIMESTAMP  TIMESTAMP,
    ANSWER            JSONB,
    AI                INT                     NOT NULL REFERENCES AIS ON UPDATE CASCADE ON DELETE SET NULL,
    AI_KIND           SMALLINT                NOT NULL REFERENCES AI_KINDS,
    AI_MODEL          SMALLINT                NOT NULL REFERENCES AI_MODELS,
    ERROR             JSONB,
    ERROR_TIMESTAMP   TIMESTAMP,
    USER_ID           BIGINT                  REFERENCES USERS ON UPDATE CASCADE ON DELETE SET NULL,
    CHAT_ID           BIGINT                  REFERENCES CHATS ON UPDATE CASCADE ON DELETE SET NULL
);
