CREATE EXTENSION IF NOT EXISTS PGCRYPTO WITH SCHEMA PUBLIC;
SET SEARCH_PATH = SYSADMIN_CHAT_BOT, PUBLIC;

CREATE TABLE IF NOT EXISTS USER_MEMORY
(
    CHAT_ID    BIGINT                  NOT NULL REFERENCES CHATS ON DELETE CASCADE ON UPDATE CASCADE,
    USER_ID    BIGINT                  NOT NULL REFERENCES USERS ON DELETE CASCADE ON UPDATE CASCADE,
    DATA_ENC   BYTEA                   NOT NULL,
    VERSION    INTEGER   DEFAULT 1     NOT NULL,
    ENABLED    BOOLEAN   DEFAULT TRUE  NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (CHAT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_CHARACTERISTICS
(
    CHAT_ID    BIGINT                  NOT NULL REFERENCES CHATS ON DELETE CASCADE ON UPDATE CASCADE,
    USER_ID    BIGINT                  NOT NULL REFERENCES USERS ON DELETE CASCADE ON UPDATE CASCADE,
    DATA_ENC   BYTEA                   NOT NULL,
    VERSION    INTEGER   DEFAULT 1     NOT NULL,
    ENABLED    BOOLEAN   DEFAULT TRUE  NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (CHAT_ID, USER_ID)
);

CREATE TABLE IF NOT EXISTS USER_MEMORY_RECALC_QUEUE
(
    CHAT_ID    BIGINT                  NOT NULL REFERENCES CHATS ON DELETE CASCADE ON UPDATE CASCADE,
    USER_ID    BIGINT                  NOT NULL REFERENCES USERS ON DELETE CASCADE ON UPDATE CASCADE,
    KIND       TEXT                    NOT NULL CHECK (KIND IN ('memory', 'characteristics')),
    REASON     TEXT                    NOT NULL,
    PRIORITY   INTEGER   DEFAULT 100   NOT NULL,
    NOT_BEFORE TIMESTAMP DEFAULT NOW() NOT NULL,
    ATTEMPTS   INTEGER   DEFAULT 0     NOT NULL,
    LOCKED_AT  TIMESTAMP,
    DONE_AT    TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT NOW() NOT NULL,
    PRIMARY KEY (CHAT_ID, USER_ID, KIND)
);
